### ISSUE TITLE
Demos of styles

### ISSUE THREAD

**Issue by pvnieo** [regolith-linux/regolith-styles#11]
Hi,

Thank you for your work. I think it would be nice if you can add photos of how the styles look like on the desktop.

Many thanks.

**Comment by kgilmer** [comment]
Thanks for the suggestion @pvnieo , I agree.  If you'd like a few Regolith laptop stickers, email me a postal address and I'll send you a few.  kgilmer at gmail.com

**Comment by kgilmer** [comment]
There is one sample on the new site for Solarized.  Once more high quality looks are available we'll create a separate page to showcase them.

**Comment by kgilmer** [comment]
Shipping looks are now showcased on the Regolith landing page.
