### ISSUE TITLE
ayu not installable

### ISSUE THREAD

**Issue by nikhiljha** [regolith-linux/regolith-styles#12]
Not sure if this is the right place to put this issue, but when I try to install regolith-look-ayu-mirage or regolith-look-ayu-dark from `apt` I get `Depends: ayu-theme but it is not installable`. I followed the instructions on the regolith homepage to add the regolith repository to my Ubuntu 19.10 install, and followed [the docs](https://regolith-linux.org/docs/customize/look/) to find the theme.

Is this a 19.10 issue?

**Comment by nikhiljha** [comment]
Installing the deb files from here (https://github.com/appelgriebsch/ayu-theme/releases) fixed it, so this is almost definitely an issue of that package not being in the 19.10 repository.

**Comment by kgilmer** [comment]
Yes you are correct @nikhiljha . This look was provided by a contributor but I don't think there is a Debian package of it yet.

**Comment by kgilmer** [comment]
Until the ayu-* packages are hosted in a Regolith PPA, you can manually install them from here: https://github.com/appelgriebsch/ayu-theme/releases

**Comment by kgilmer** [comment]
Fixed in 1.3.1.
