### ISSUE TITLE
Some apps do not following the theme

### ISSUE THREAD

**Issue by cheginit** [regolith-linux/regolith-styles#14]
Some apps like GIMP and slack don't follow the theme button and window style. For example, this is what GIMP looks like. Notice the ancient-looking of the interface!

![Screenshot from 2020-02-18 10-35-31](https://user-images.githubusercontent.com/13016644/74756615-7273e480-523a-11ea-8361-e6af728c7ef0.png)

Firefox doesn't have this issue. For example, this is how the open dialog box looks like:
![Screenshot from 2020-02-18 10-36-12](https://user-images.githubusercontent.com/13016644/74756703-9800ee00-523a-11ea-8a17-ada388c3e7cb.png)

**Comment by kgilmer** [comment]
Were these apps installed via snaps?  I believe there are custom flags required to all snap-based apps to get access to the local theme resources...

**Comment by cheginit** [comment]
No, I installed GIMP from its PPA. I installed slack from snap though and it has an issue with the tray icon. I looked at the syslog and it says that icon cannot be found for snap:
```
Mar  5 00:14:48 titan gnome-software[3579]: g_path_get_basename: assertion 'file_name != NULL' failed
Mar  5 00:14:48 titan gnome-software[3579]: g_regex_match_full: assertion 'string != NULL' failed
Mar  5 00:14:48 titan gnome-software[3579]: g_path_get_basename: assertion 'file_name != NULL' failed
Mar  5 00:14:48 titan gnome-software[3579]: g_regex_match_full: assertion 'string != NULL' failed
Mar  5 00:14:48 titan gnome-software[3579]: Failed to load snap icon: local snap has no icon
Mar  5 00:14:48 titan gnome-software[3579]: failed to call gs_plugin_refine_app on snap: Invalid string value converting to GVariant
Mar  5 00:14:48 titan gnome-software[3579]: g_variant_new_variant: assertion 'value != NULL' failed
Mar  5 00:14:48 titan gnome-software[3579]: g_variant_new_variant: assertion 'value != NULL' failed
Mar  5 00:14:48 titan gnome-software[3579]: failed to call gs_plugin_refine_app on snap: Invalid string value converting to GVariant
```

**Comment by cheginit** [comment]
The issue with the snap icon is because of snap. So I found a way of automatically installing the latest version from a deb file and uninstalled the snap version.
```bash
version=$(curl -s "https://slack.com/release-notes/linux" | awk -v FS="(<h2>|</h2>)" '{print $2}' | grep -m1  Slack | awk -F' ' '{ print $2}') && \
wget https://downloads.slack-edge.com/linux_releases/slack-desktop-${version}-amd64.deb
```

**Comment by kgilmer** [comment]
Are we good here @cheginit ?

**Comment by cheginit** [comment]
Yeah, I think nothing can be done from Regolith side.
