### ISSUE TITLE
Latest update error: broken pipe

### ISSUE THREAD

**Issue by dvogeldev** [regolith-linux/regolith-styles#16]
Steps:
sudo apt update && sudo apt upgrade
Results:
```
Preparing to unpack .../regolith-look-lascaille_2.4.12_amd64.deb ...
Unpacking regolith-look-lascaille (2.4.12) ...
dpkg: error processing archive /var/cache/apt/archives/regolith-look-lascaille_2.4.12_amd64.deb (--unpack):
 trying to overwrite '/usr/share/backgrounds/joel-filipe-unsplash.jpg', which is also in package regolith-look-ayu-mirage-regolith 2.4.8
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/regolith-look-lascaille_2.4.12_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```
Attempted removal of /var/c/a/a/regolith-look-lascaille... and /usr/s/b/joel-filipe... Then sudo apt --fix-broken install

Resulted in same error.

**Comment by dvogeldev** [comment]
Attempted rollback did not work.

` awk 'BEGIN{ start="0" } { if($0 ~ /Log started: 2020-04-13/) { start="1" } if ( start == "1" && $0 ~ /Unpacking.*over/) {gsub(/[\s\t)( ]+/,"",$5); printf("%s=%s ", $2 , $5)}}' /var/log/apt/term.log
`
resulted:
`regolith-i3xrocks-config=3.0.8 i3xrocks-cpu-usage=3.0.8 i3xrocks-memory=3.0.8 i3xrocks-net-traffic=3.0.8 i3xrocks-time=3.0.8 regolith-styles=2.4.8`

Attempted rollback with error " Version '2.4.8' for 'regolith-styles' was not found"

**Forgot to mention, regolith repo=unstable, Ubuntu 19.10**

**Comment by kgilmer** [comment]
Hi @dvogeldev , yes `unstable` is a little choppy at the moment.  I've made a few fixes in the past couple of hours.  Can you try upgrading your packages again?

**Comment by dvogeldev** [comment]
Thanks @kgilmer the fixes worked. Thanks for the great distro, stumbled on this a couple of weeks ago
