### ISSUE TITLE
Gruvbox style

### ISSUE THREAD

**Issue by ekans** [regolith-linux/regolith-styles#17]
Locally I created a style based on the gruvbox colors.
The style is based on the nord style with some simple updates:
- color -> gruvbox colors
- rofi.rasi -> gruvbox colors
- gtk theme -> [gruvbox-gtk](https://github.com/3ximus/gruvbox-gtk).

Do you think it could be interesting to create a pull request ?

**Comment by kgilmer** [comment]
It could be interesting, yes!

**Comment by ekans** [comment]
Currently I use [gruvbix-gtk](https://github.com/3ximus/gruvbox-gtk) but there is no debian package in ubuntu. I just clone the repo and install it  in ~/themes.

So what do you recommend?

**Comment by kgilmer** [comment]
We will need to package it and host it in the Regolith PPAs before being able to host the style.  I'll create an issue for that.

**Comment by amanusk** [comment]
I'd be very interested in the this feature, or at least explanation how to set it up. Thanks

**Comment by stonepreston** [comment]
I am also very interested in this, any updates?

**Comment by rtud** [comment]
Here, here - any news?

**Comment by kgilmer** [comment]
@ekans if you can submit your changes in a PR I will do the packaging work for the GTK theme.  Yeah?

**Comment by ekans** [comment]
Sorry for the delay!
I just created a PR initializing a gruvbox style.

@kgilmer I can package the theme if you give me an example.
