### ISSUE TITLE
Ubuntu look: Rofi text is difficult to read

### ISSUE THREAD

**Issue by morten-b** [regolith-linux/regolith-styles#23]
Due to low contrast between text and background the selected element of Rofi is difficult to read. Please see image: [https://imgur.com/a/oV2i5Dj](url)

Either the background could be made a lighter gray or the selected color could be changed to something else than the signature color of Ubuntu (#762572) 

Is is in the file: ubuntu/rofi.rasi

**Comment by kgilmer** [comment]
Thanks for the feedback @morten-b .  What do you think about this?

![image](https://user-images.githubusercontent.com/49683/92316270-5b160200-efa6-11ea-86d9-72c0f76f14ac.png)

**Comment by morten-b** [comment]
Looks perfect to me

**Comment by kgilmer** [comment]
Resolved
