### ISSUE TITLE
Dracula Style

### ISSUE THREAD

**Issue by drewofdoom** [regolith-linux/regolith-styles#24]
I have a ready-to-go style at https://github.com/drewofdoom/regolith-styles (subdir `dracula`).

In order for this to get integrated, we would need to package the Dracula GTK theme, found here: https://github.com/dracula/gtk

Ideally, we would also integrate the official Dracula Gnome Terminal theme, but that may get messy considering that the colors currently pull from ST: https://github.com/dracula/gnome-terminal

Another option would be to ship the defaults that I have created, but add an Xresources entry to allow users to choose an alternate profile and not have it overwritten ever time the look refreshes.

Final consideration - I have modified the Regolith Rofi theme with Dracula colors, but there is an official Dracula Rofi theme available if we would prefer to use it. Personally, I like the style of the Regolith theme better...: https://github.com/dracula/rofi

**Comment by drewofdoom** [comment]
One more thing...

The official Dracula i3 theme also has specific colors for i3bar, but I cannot see any way to make that change in the i3-wm config. Would it be possible to add these as configurable resources?

```
general {
  output_format = "i3bar"
  colors = true
  color_good = "#50FA7B"
  color_degraded = "#F1FA8C"
  color_bad = "#FF5555"
}
```
from https://github.com/dracula/i3

**Comment by kgilmer** [comment]
Hi @drewofdoom !

> Ideally, we would also integrate the official Dracula Gnome Terminal theme, but that may get messy considering that the colors currently pull from ST: https://github.com/dracula/gnome-terminal

The default term now is gnome-terminal and there is a script (/usr/bin/create-regolith-term-profile) adapted from the Nord project that generates a gnome-terminal profile from the colors specified via Regolith's Xresource definitions.  So, if the color definitions are good, then the terminal color setup should "just work" after running `regolith-look refresh`.  The Regolith gnome-terminal profile is regenerated w/ this script.

Regarding i3bar, afaik all color options are currently mapped to Xresources.  Are you talking about a source patch?  I don't see that copied stanza in the source repo, but could have missed it...

You're welcome to create a PR and we can work on packaging the GTK theme as a parallel task.  There are a few other new looks under way and some of Xresources have already been merged from them as well.  Your call.

**Comment by kgilmer** [comment]
Oh, that color configuration is for i3status.  Regolith uses i3blocks by default instead.  The color mappings for i3blocks are probably what needs mapping from the color definition you specified.

**Comment by drewofdoom** [comment]
Hey @kgilmer!

Right about i3blocks. That's my mistake! I'll look into options to adjust the i3blocks warn/crit/etc colors with the options already provided.

As for the terminal, I do know it's Gnome Terminal, but the file names still reference st. ;)

The official Dracula theme sets some things that I'm not sure are doable in your implementation. The scheme I set is workable, just not as slick as the official one.

**Comment by drewofdoom** [comment]
Did some digging and learning and it looks like the i3xrocks/i3blocks config is already good to go. Looks like colors pull from the theme colors, so I was just being dumb there. ;)

So it looks like the only thing that's really needed is to package up Dracula's GTK theme!

**Comment by kgilmer** [comment]
I'm doing the packaging of dracula-gtk here: https://github.com/regolith-linux/dracula-gtk

**Comment by kgilmer** [comment]
@drewofdoom  I am ready to merge a PR...

**Comment by drewofdoom** [comment]
@kgilmer pull request created!

**Comment by kgilmer** [comment]
And now you're a project contributor, welcome and thank you!  (https://github.com/regolith-linux/regolith-styles)
