### ISSUE TITLE
Dracula: terminal text in color 11 invisible

### ISSUE THREAD

**Issue by twvd** [regolith-linux/regolith-styles#32]
St.color0 and St.color11 are the same value, which means that i.e. some syntax highlighted keywords in vim become invisible.

```
St.color0:           color_base00
St.color11:          color_base00
```

Changed it to pink myself, but I'm sure the author can come up with a proper choice that may blend better :)

**Comment by kgilmer** [comment]
@drewofdoom what do you think?  Pink?

**Comment by drewofdoom** [comment]
Pink is most likely the right answer here. I kinda guessed on some of these, as I was not sure what colors match to what on in the `st` schema.

Just changed it to `color_pink` on my local version and nothing appears to be mangled.

**Comment by kgilmer** [comment]
here is what I came up with:

![image](https://user-images.githubusercontent.com/49683/92409783-a2130d00-f0f6-11ea-9736-513453d30b5a.png)


Feel free to suggest alternative mappings!

**Comment by priestoferis** [comment]
Shouldn't this issue be closed if it is "done"?
