### ISSUE TITLE
Dracula bar icons broken

### ISSUE THREAD

**Issue by priestoferis** [regolith-linux/regolith-styles#33]
I installed Dracula from repo and used the regolith look selector.

The look in Dracula:
![image](https://user-images.githubusercontent.com/6343487/97268679-868dce00-182c-11eb-8f72-263c55575ff5.png)

How it looks in laiscalle (proper):

![image](https://user-images.githubusercontent.com/6343487/97268875-da98b280-182c-11eb-9e69-cffe1c899f65.png)

**Comment by moritzheiber** [comment]
Could this be related to regolith-linux/regolith-desktop#492?

**Comment by priestoferis** [comment]
Possible, although I'm on 20.04 LTS.

**Comment by priestoferis** [comment]
The update that came out today on unstable seems to have fixed it, so I'm closing the issue.
