### ISSUE TITLE
The Options of terminal transparency don't work

### ISSUE THREAD

**Issue by takumiando** [regolith-linux/regolith-styles#34]
I added the options of terminal transparency to ``/etc/regolith/styles/gnome``.
Other options work successfully, but the transparency options don't.

```
...
gnome.terminal.use-transparent-background true
gnome.terminal.background-transparency-percent 50
```

I could apply this changes from preference menu of gnome terminal, but I'd like to save/load them as style files. 
Regolith version is 1.5.0.

```
$ cat /etc/regolith/version
REGOLITH_VERSION=1.5.0
```

I referred this page.
https://regolith-linux.org/docs/reference/xresources/

Do I need something else?

**Comment by moritzheiber** [comment]
Please read up on [the docs about overriding Xresources](https://regolith-linux.org/docs/howto/override-xres/). If there are other enhancements or issue you might have you can file another issue for them :slightly_smiling_face:

**Comment by kgilmer** [comment]
Actually this is my bad, I did not release the change to the package needed for this feature to work.  This will go into 1.5.1.  Thanks for the bug report @takumiando  :smile:

**Comment by kgilmer** [comment]
fix: https://github.com/regolith-linux/regolith-ftue/commit/47420570d09b18f676a0d239daf7784284e75cc9

Change is building into `unstable` now.

**Comment by kgilmer** [comment]
This should be resolved, closing.
