### ISSUE TITLE
Options of terminal transparency don't work

### ISSUE THREAD

**Issue by takumiando** [regolith-linux/regolith-styles#35]
I added these options to ``~/.config/regolith/Xresources ``.
But  ``gnome.terminal.background-transparency-percent: 80`` and ``gnome.terminal.use-transparent-background: true`` don't work.

```
$ cat ~/.config/regolith/Xresources 
gnome.terminal.background-transparency-percent: 80
gnome.terminal.use-transparent-background: true
gnome.terminal.font: Terminus-ja 12
i3-wm.gaps.inner.size: 15
```

Do I need something else?

**Comment by moritzheiber** [comment]
Reference: regolith-linux/regolith-ftue#1

@kgilmer Did we ever package that added functionality and release it?
