### ISSUE TITLE
Dracula: Current window layout border isn't visible

### ISSUE THREAD

**Issue by michael-barker** [regolith-linux/regolith-styles#40]
From the [Regolith docs](https://regolith-linux.org/docs/interface/apps/#window-layout).

> A blue border will appear on the bottom or right of the window to indicate the current layout mode.

With other themes I can see this border but it I'm unable to see it with the Dracula theme.

**Comment by HieuTranTH** [comment]
I believe it is the way the theme is, since in /etc/regolith/styles/dracula/i3-wm file `i3-wm.client.focused.color.border` and `i3-wm.client.focused.color.indicator` both use "color_blue". You can simply change that default in your Xresources to fit your preference.

**Comment by michael-barker** [comment]
I can override it although I was thinking the theme should use different colors for the border and indicator.
