### ISSUE TITLE
help with customization of border color

### ISSUE THREAD

**Issue by dowcet** [regolith-linux/regolith-styles#45]
I'm a newbie to customizing i3 so if this isn't the most appropriate forum for this question please feel free to direct me elsewhere.

I'm using the `solarized-dark` look, but I want to make the border highlighting of active windows higher contrast. I was able to increase the border thickness a bit by modifying `/etc/regolith/styles/solarized-dark/theme` to say `#define i3wm_window_border_size         2`. But I haven't found a way to change the color. 

I've noticed that other themes like midnight have their own `i3-wm` files. I tried adding one to `solarized-dark` with the line `i3-wm.client.focused.color.border: color_magenta`, refreshing and opening a new window but that didn't work.

What's the best way to accomplish a small change like this?

**Comment by kgilmer** [comment]
Hi @dowcet ,

  The Xresource key your looking for is `i3-wm.client.focused.color.child_border`.  You can find a description of all Xresource keys here: https://regolith-linux.org/docs/reference/xresources/  (although the key in question is currently undocumented :( )

 It is not recommended to directly edit the i3 config file is that often will cause things to break after upgrades.  Rather we recommend to set Xresource values using Xresource overrides.  See here for details: https://regolith-linux.org/docs/howtos/override-xres/

An example to set the border to red, add this line to the file `~/.config/regolith/Xresources`:

```
i3-wm.client.focused.color.child_border: #FF0000
```

Please re-open the issue if this doesn't fix you up @dowcet

**Comment by ghost** [comment]
This works for me, but only for a few windows like the terminal. For browser windows no red border appears. Do you know why?
