### ISSUE TITLE
[QUESTION] how to change the system-prefers-mode

### ISSUE THREAD

**Issue by polaroidkidd** [regolith-linux/regolith-styles#47]
In general I really like the default theme. However, I don't like having every application use "dark" mode. I've been trying to set it using 

```
[Settings]
gtk-application-prefer-dark-theme=0
```

in `~/.config/gtk-3.0/settings.ini` and looking for a variable in this repository which communicates to the system and the apps the dark-mode preference.

Is it even possible to tell the system to prefer light mode without changing the entire theme to a light-mode theme?

Any help would be appreciated in this regard.

**Comment by kgilmer** [comment]
Hi @polaroidkidd , 

> Is it even possible to tell the system to prefer light mode without changing the entire theme to a light-mode theme?

I don't believe it is possible with Regolith.  At least, this is not a feature that Regolith supports.  For Regolith it's essentially the GTK theme and the color palatte specified in your Regolith [Xresources](https://github.com/regolith-linux/regolith-styles/blob/master/lascaille/color).  I am guessing this is a feature of other desktop environments such as gnome shell.  This thread may be of interest: https://www.reddit.com/r/i3wm/comments/kiy0v0/i3_and_system_default_lightdark_theme_settings/

**Comment by polaroidkidd** [comment]
I have searched for hours trying to find some information which is contained in that Reddit post! Thanks!
