### ISSUE TITLE
typeface-ubuntu does not change the terminal

### ISSUE THREAD

**Issue by powersj** [regolith-linux/regolith-styles#9]
It seems odd that using the typeface-ubuntu config file keeps the terminal with Source Code Pro. I had expected it to change all the fonts, including the terminal, to use Ubuntu [Mono]. Something like:

https://gist.github.com/powersj/546e2d558f4a7b26e56aacdaea6c5aee

Is there a decision decision behind leaving the terminal, but changing the others?

**Comment by kgilmer** [comment]
Hi @powersj , I like your edit.  If you'd like to create a PR since you've already made the change feel free!  Otherwise I'll make the change before R1.3 release at some point.
